### ISSUE TITLE
Map inside a group tab interface doesn't take the full width / height

### ISSUE THREAD

**Issue by emilienbidet** [hanneskuettner/directus-extension-group-tabs-interface#1]
Hello !

I have an issue on creating a group tab interface. 
When I add a map field inside a group tab interface, the map doesn't fit the container.

<img width="808" alt="CleanShot 2023-06-21 at 14 01 06@2x" src="https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/44983373/39bc8da3-4adf-493e-84ae-795e04d61bed">

Thank you very much
Emilien

**Comment by hanneskuettner** [comment]
Looks like a fairly simple problem that is caused due to this extension hiding the inactive tabs for performance reasons instead of destroying them. I've adjusted it to work the same as the accordion now and that seems to fix the issue and will publish a fix now.

Love the emojis in the tab headers, btw.
